import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Karishma",
    lastName: "Gajria Agarwal",
    username: "karishma@gmail.com",
    password: "abc@123",
    userHandler: "karishma-gajria-768107138",
    profileTitle: 'Frontend dev | React JS',
    bio: "Software developer (react js) at LMS Solutions (India) Pvt. Ltd. | Neog'22 sudent",
    workPlace:"LMS Solutions (India) Pvt. Ltd. | Neog'22 ",
    workExperience:[{workplace:"LMS Solutions (India) Pvt. Ltd.", role:"SDE |React js", duration:'feb 2021 - Present (1.3years)'},
    {workplace:"Parkhya It solutions Pvt. Ltd.", role:"SDE | iOS dev", duration:'feb 2017 - May 2018'}
    ],
    education:'B.Tech(cs)',
    educationHistory:[{education:"B.tech", institute:"RGPV", passoutYear:'2013'},{education:"SSC", institute:"CBSE", passoutYear:'2009'}],
    location: 'Indore , Madhya Pradesh, India',
    link: "https://www.linkedin.com/in/karishma-gajria-768107138/",
    profilePic: "https://media-exp1.licdn.com/dms/image/C4D03AQEzoWzVUUpqMw/profile-displayphoto-shrink_200_200/0/1517496782090?e=1658361600&v=beta&t=ENUIdUSsc6H5bBBLnlTJtZUg4cZD9dm0uc8FAGQU7s8",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Adarsh",
    lastName: "Balika",
    username: "balika@gmail.com",
    userHandler: "adarshbalika",
    password: "adarshBalika123",
    profileTitle: 'Student',
    location: 'Indore , Madhya Pradesh, India',
    bio: "this is my bio balika",
    workPlace:'Choithram hospital',
    education:'MD - MGM college',
    workExperience:[{workplace:"MGM Hospital", role:"Jr. Dr.", duration:'feb 2021 - Present (1.3years)'},
    {workplace:"choithram Hospital", role:"Dr. Assistant", duration:'feb 2017 - May 2018'}
  ],
  educationHistory:[{education:"B.sc", institute:"RGPV", passoutYear:'2013'},{education:"SSC", institute:"CBSE", passoutYear:'2009'}],
    link: "https://adarshbalika.netlify.app",
    profilePic:
      "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457790/baatchit/woman_ojbd7v.png",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Dr Hemant",
    lastName: "Patel",
    username: "hemant@gmail.com",
    userHandler: "dr-hemant-patel-568aba19b",
    password: "abc@123",
    profileTitle: 'Neurologist',
    location: 'Indore , Madhya Pradesh, India',
    bio: "Mbbs and managing director at health care hospital",
    education:'MD - MGM college',
    workPlace:'Greater Kailash hospital',
    workExperience:[{workplace:"Greater Kailash hospital", role:"Managing director", duration:'feb 2021 - Present (1.3years)'},
    {workplace:"Vedanta Hospital", role:"Sr. Dr.(Neurologist)", duration:'feb 2017 - May 2018'}
  ],
  educationHistory:[{education:"Masters", institute:"AIIMS", passoutYear:'2013'},{education:"Undergrad", institute:"AIIMS", passoutYear:'2011'},{education:"SSC", institute:"CBSE", passoutYear:'2009'}],
    link: "https://www.linkedin.com/in/dr-hemant-patel-568aba19b/",
    profilePic:
      "https://media-exp1.licdn.com/dms/image/D5603AQEMPo6wTKVQdg/profile-displayphoto-shrink_200_200/0/1642091037911?e=1658361600&v=beta&t=aWfwzEbOzteBGkjkxF26CiaHZ8uf1_Q2bA5NdVOxpPE",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Dr Ritesh",
    lastName: "Malik",
    username: "ritesh@gmail.com",
    userHandler: "drriteshmalik",
    password: "abc@123",
    profileTitle: 'Enterprenuer(Healthcare)',
    workPlace:'abz healthcare pvt. ltd.',
    education:'MBBS - AIIMS',
    location: 'Indore , Madhya Pradesh, India',
    workExperience:[{workplace:"abz healthcare pvt. ltd.", role:"CEO", duration:'feb 2021 - Present (1.3years)'},
    {workplace:"Vedanta Hospital", role:"Managing director", duration:'feb 2017 - May 2018'}
  ],
  educationHistory:[{education:"MBA", institute:"IIM", passoutYear:'2015'},{education:"Masters", institute:"AIIMS", passoutYear:'2013'},{education:"Undergrad", institute:"AIIMS", passoutYear:'2011'},{education:"SSC", institute:"CBSE", passoutYear:'2009'}],
    bio: "Entrepreneurship Development in India | Coworking | Angel Investment | Innovation | Management | Strategy | Healthcare | Technology | Wearables | Hardware | Education | Motivation | Inspiration",
    link: "https://www.linkedin.com/in/drriteshmalik/",
    profilePic:
      "https://media-exp1.licdn.com/dms/image/C5103AQGgQQ--JYft5w/profile-displayphoto-shrink_200_200/0/1578826017486?e=1658361600&v=beta&t=YC63kY3G1mU0PbiKSGmXtiQ4j_OXPRI2IEIgG5gRq8M",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  // {
  //   _id: uuid(),
  //   firstName: "Omkar",
  //   lastName: "Shah",
  //   username: "omkar@gmail.com",
  //   userHandler: "Omkar123",
  //   password: "111",
  //   bio: "this is my bio omkar",
  //   link: "https://omkar.netlify.app",
  //   profilePic:
  //     "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457790/baatchit/man_3_dfq8h3.png",
  //   createdAt: formatDate(),
  //   updatedAt: formatDate(),
  // },
  // {
  //   _id: uuid(),
  //   firstName: "Gaurav",
  //   lastName: "Verma",
  //   username: "gaurav@gmail.com",
  //   userHandler: "Gaurav123",
  //   password: "111",
  //   bio: "this is my bio gaurav",
  //   link: "https://gaurav.netlify.app",
  //   profilePic:
  //     "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457646/baatchit/hacker_jednhr.png",
  //   createdAt: formatDate(),
  //   updatedAt: formatDate(),
  // },
  // {
  //   _id: uuid(),
  //   firstName: "Sunil",
  //   lastName: "Agarwal",
  //   username: "sunil@gmail.com",
  //   userHandler: "Sunil123",
  //   password: "111",
  //   bio: "this is my bio suil",
  //   link: "https://sunil.netlify.app",
  //   profilePic:
  //     "https://res.cloudinary.com/dgwzpbj4k/image/upload/v1650457645/baatchit/man_rp4ore.png",
  //   createdAt: formatDate(),
  //   updatedAt: formatDate(),
  // },
];
